### ISSUE TITLE
AWS provider broken

### ISSUE THREAD

**Issue by coolpalani** [ramrexx/CloudForms_Amazon_Essentials#1]
Hi

As past few days AWS provider was perfectly working and due to some reason this provider broken.
When I try to re-validate the evm.log shows as below 

[----] E, [2018-03-29T23:54:02.468024 #2792:109f118] ERROR -- : MIQ(ManageIQ::Providers::Amazon::CloudManager.connection_rescue_block) Error Class=Aws::EC2::Errors::AuthFailure, Message=AWS was not able to validate the provided access credentials

But none of issue in the Access Key ID and Secret Access Key
When I use the same key in the fresh appliance, it's working.
How do we trace this problem.
Also I am facing one more problem, I removed the OpenShift container platform but node name, project details are still showing in the CloudForms.

Current CloudForms version
`[root@cfm ~]# rpm -q cfme`
`cfme-5.9.0.22-1.el7cf.x86_64`
`[root@cfm ~]# which ruby`
`/opt/rh/rh-ruby23/root/usr/bin/ruby`
`[root@cfm ~]# ruby -v`
`ruby 2.3.6p384 (2017-12-14 revision 61254) [x86_64-linux]`
`[root@cfm ~]# bundle show  | grep -i aws`
`  * aws-sdk (2.9.44)`
 ` * aws-sdk-core (2.9.44)`
`  * aws-sdk-resources (2.9.44)`
 ` * aws-sigv4 (1.0.2)`

`[root@cfm ~]# bundle show  | grep -i amazon`
 ` * amazon_ssa_support (0.1.0 8691fb8)`
`  * manageiq-providers-amazon (0.1.0 9620e26)`

Appliance is properly syncing with NTP server as well.

**Comment by ramrexx** [comment]
@coolpalani - I cannot help you with troubleshooting providers. You will need to open a support case with Red Hat for this. This issue you are experiencing is not related to this git repo because of this i am closing this issue.
